[package]
name = "project_tracker_server"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Peanutt42/project_tracker"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
filetime = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, optional = true }
sha2 = "0.10.8"
aes-gcm = "0.10.3"
pbkdf2 = "0.12.2"

[features]
async_tokio = ["dep:tokio"]