[package]
name = "project_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.0", features = ["image", "tokio"] }
iced_aw = { version = "0.9.3", default-features = false, features = ["spinner", "split", "quad", "floating_element", "icons", "context_menu"] }
tokio = { version = "1.0", features = ["fs"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.24"
once_cell = "1.19.0"
directories = "5.0.1"
dark-light = "1.1.1"
rand = "0.8.5"
