[package]
name = "project_tracker"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["project_tracker_gui", "iced_drop"]

[dependencies]
project_tracker_gui = { path = "project_tracker_gui" }
iced = { workspace = true }
iced_aw = { workspace = true }
iced_fonts = "0.1.1"
image = "0.24"

[workspace.dependencies]
iced = { version = "0.13.1", features = ["image", "tokio", "canvas", "advanced"] }
iced_aw = { version = "0.11", default-features = false, features = ["spinner", "card", "quad", "date_picker"] }

[features]
hot_reload = ["project_tracker_gui/hot_reload"]

[build-dependencies]
winresource = "0.1.17"