[package]
name = "project_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["svg"] }
iced_aw = { version = "0.8.0", default-features = false, features = ["grid", "card", "modal"] }
image = "0.25.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
