[package]
name = "project_tracker"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Peanutt42/project_tracker"

[workspace]
members = [
	"project_tracker_server",
	"iced_drop"
]

[dependencies]
project_tracker_server = { path = "project_tracker_server" }
iced = { workspace = true }
iced_aw = { workspace = true }
iced_drop = { path = "iced_drop" }
iced_fonts = "0.1.1"
tokio = { workspace = true }
notify-rust = "4"
serde = { workspace = true }
serde_json = { workspace = true }
indexmap = { version = "2.4", features = ["serde"] }
once_cell = "1.19.0"
directories = "5.0.1"
dark-light = "1.1.1"
rand = "0.8.5"
rfd = "0.14.1"
open = "5.1.4"
walkdir = "2.5"
filetime = { workspace = true }
pretty-duration = "0.1.1"
chrono = { workspace = true }
fuzzy-matcher = "0.3.7"
libc = "0.2"
image = "0.24"
thiserror = { workspace = true }

[dev-dependencies]
tokio = { version = "1.4", features = ["fs", "rt", "macros", "net", "io-util"] }

[workspace.dependencies]
iced = { version = "0.13.1", features = ["image", "tokio", "canvas", "advanced", "lazy", "markdown", "highlighter"] }
iced_aw = { version = "0.11", default-features = false, features = ["spinner", "card", "quad", "date_picker", "drop_down"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.4", features = ["fs", "net", "io-util"] }
chrono = { version = "0.4.38", features = ["serde"] }
filetime = "0.2"
thiserror = "1.0"

[build-dependencies]
winresource = "0.1.17"