[package]
name = "project_tracker"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["project_tracker_gui"]

[dependencies]
project_tracker_gui = { path = "project_tracker_gui" }
iced = { version = "0.12.0", features = ["image", "tokio"] }
image = "0.24"

[build-dependencies]
winresource = "0.1.17"
