[package]
name = "project_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
dark-light = "1.1.1"
iced = { version = "0.12.0", features = ["image", "tokio"] }
iced_aw = { version = "0.9.3", default-features = false, features = ["spinner", "split", "quad", "icons"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.24"
tokio = { version = "1.0", features = ["fs"] }
once_cell = "1.19.0"
