[package]
name = "project_tracker"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["project_tracker_gui", "iced_drop"]

[dependencies]
project_tracker_gui = { path = "project_tracker_gui" }
iced = { workspace = true }
iced_aw = { workspace = true }
image = "0.24"

[workspace.dependencies]
iced = { version = "0.13", features = ["image", "tokio", "canvas", "advanced"] }
iced_aw = { version = "0.10", default-features = false, features = ["spinner", "card", "quad", "icons", "date_picker"] }

[build-dependencies]
winresource = "0.1.17"